POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "woda",
    "author": "Siekoś",
    "url": "www.cos.pl",
    "likes": 49
}

####
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "haslo"
}